# Generated by Django 3.0.6 on 2020-05-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200530_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='tasks_abandoned',
            new_name='recipies_created',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='tasks_archived',
        ),
    ]
