# Generated by Django 3.0.6 on 2020-06-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocieresshoppinglist',
            old_name='author',
            new_name='uesr',
        ),
    ]
